#! /usr/bin/python3
# Copyright 2020 Pascal COMBES <pascom@orange.fr>
#
# This file is part of Pythography.
#
# Pythography is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pythography is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pythography. If not, see <http://www.gnu.org/licenses/>

import os

from argparse import ArgumentParser
from appdirs import AppDirs
from configparser import ConfigParser
from warnings import warn as warning

from bibtex import BibFile

if __name__ == '__main__':
    # Parse command line arguments:
    argParser = ArgumentParser(
        description="Rename linked PDF files according to BibTeX key",
        epilog="""License: GPL v3, see <http://www.gnu.org/licenses/>
Copyright (c) 2019-2020 Pascal COMBES <pascom@orange.fr>""")
    argParser.add_argument('bibFile',
        nargs=1,
        help="BibTeX file where to search for linked files"
    )
    args = argParser.parse_args()

    # Load bibTeX file:
    bibFile = BibFile(args.bibFile[0])
    bibFile.read()
    bibFile.updateKeys()

    # Backup bibTeX file:
    os.rename(args.bibFile[0], args.bibFile[0] + '.old')

    # Move files and update file entries:
    for bibItem in bibFile:
        try:
            oldPath = bibItem['file']
        except (KeyError):
            warning(f"No file field in: {bibItem}")
            continue

        if oldPath.startswith(':'):
            oldPath = oldPath.split(':')[1]
        if os.path.isabs(oldPath):
            oldPath = os.path.relpath(oldPath, os.path.dirname(args.bibFile[0]))

        newPath = os.path.join(os.path.dirname(oldPath), bibItem['key'] + '.pdf')
        if os.path.exists(newPath):
            warning(f"File {newPath} already exists")
            continue

        print(f"Moving {oldPath} to {newPath}")
        try:
            os.rename(os.path.join(os.path.dirname(args.bibFile[0]), oldPath),
                      os.path.join(os.path.dirname(args.bibFile[0]), newPath))
            bibItem['file'] = newPath
        except FileNotFoundError:
            warning(f"Could not find {oldPath}")

    # Write bibTeX file:
    bibFile.write()

